name: 'Upstream Sync'

on:
  schedule:
    - cron: '0 4 * * 1-5'   
  workflow_dispatch:  


jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    name: Sync latest commits from upstream repo  
    steps:
    - name: Checkout target repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GH_TOKEN }}
        persist-credentials: false
    - name: Merge from upstream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        UPSTREAM: YoYoGames/GameMaker-Manual
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"

        git --version

        ls
